### ISSUE TITLE
Formalizar tiempos en The Pool

### ISSUE THREAD

**Issue by xiam** [golangmx/gophergala-2015#2]
Hola @alce!

Me di cuenta que la dinámica en The Pool no está confirmada por completo, por lo que de momento no podemos publicar detalles fijos de horario y dinámica formal.

Lo que propongo es vernos allá el viernes 23 de 7pm a 9pm (para el kick off, la discusión previa y ayudar a equipos que lleguen con dudas de Go o de la vida), tener acceso el 24 desde 9am a 6pm (para darle con todo) y el 25 de 11pm a 7pm (para terminar detalles y enviar participación). ¿Qué opinas? ¿crees que The Pool pueda darnos ese acceso?

Además, creo que en https://github.com/golangmx/gophergala-2015 nos falta un enlace a KIWI!

**Comment by alce** [comment]
Lo que tenemos acordado con The Pool es tener acceso las 48 horas continuas. Esto lo tenemos confirmado ya. Lo que yo me estaba imaginando era vernos el Viernes a las 7 PM y trabajar la noche del viernes, todo el sábado y desbandarnos el Sábado en la noche, descansar y trabajar remoto o regresar el domingo frescos a hacer la entrega.

Los horarios que propones están menos mortales, me parecen más coherentes, y quizá sea más fácil para The Pool... aunque hay quienes preferimos trabajar de noche.

Qué opinan los demás?

**Comment by oscarryz** [comment]
Me parecen bien los horarios que propone Carlos,  yo igual voy a estar en
mi casa todo el tiempo.

**Comment by Verolop** [comment]
Estoy de acuerdo con los horarios que proponen.
No me han aceptado en Slack (me registré el viernes), ¿han organizado algo más por ahí?

**Comment by oscarryz** [comment]
Nomas que si tienes alguna propuesta de proyecto la escribas en la wiki y
que mañana lunes hacemos los equipos y pues ya

**Comment by xiam** [comment]
Gracias, entonces dejé esos tiempos como formales. Así no le cargamos tanto la mano al personal de The Pool (y promovemos el baño diario entre participantes).
